# Generated by Django 5.0.4 on 2024-05-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='AD_roommate',
            fields=[
                ('Ad_Id', models.AutoField(primary_key=True, serialize=False)),
                ('facebook', models.CharField(max_length=45, null=True)),
                ('instagram', models.CharField(max_length=45, null=True)),
                ('study_level', models.CharField(max_length=45)),
                ('note', models.CharField(max_length=45, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.user')),
            ],
            options={
                'db_table': 'AD_roommate',
            },
        ),
    ]
