# Generated by Django 5.0.4 on 2024-05-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_user_city_user_email_user_fullname_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_roommate',
            name='user',
            field=models.ForeignKey(db_column='Id', on_delete=django.db.models.deletion.CASCADE, related_name='ad_roommates', to='ads.user'),
        ),
    ]
