# Generated by Django 5.0.4 on 2024-05-02 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0003_alter_ad_roommate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id_house', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_rent', models.FloatField()),
                ('security_deposit', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('date_available', models.DateField()),
                ('photo1', models.CharField(max_length=255)),
                ('photo2', models.CharField(max_length=255)),
                ('photo3', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=1000)),
                ('Property_Type', models.CharField(max_length=45)),
                ('datePosted', models.DateField(default=datetime.date.today)),
                ('university', models.CharField(max_length=45)),
                ('a_c', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('waterelect', models.BooleanField()),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='house', to='ads.user')),
            ],
        ),
    ]
