# Generated by Django 5.0.4 on 2024-05-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='house',
            table='house',
        ),
    ]
