# Generated by Django 5.0.4 on 2024-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='a_c',
            field=models.BooleanField(db_column='a/c'),
        ),
        migrations.AlterField(
            model_name='house',
            name='balcony',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='furnished',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='waterelect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='wifi',
            field=models.IntegerField(),
        ),
    ]
