# Generated by Django 5.0.4 on 2024-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_a_c_alter_house_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='a_c',
            field=models.IntegerField(db_column='a/c'),
        ),
    ]
