# Generated by Django 5.0.4 on 2024-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_house_a_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='photo1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo3',
            field=models.ImageField(upload_to=''),
        ),
    ]
