# Generated by Django 5.0.4 on 2024-05-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_house_photo1_alter_house_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='house',
            name='photo1',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
