# Generated by Django 5.0.4 on 2024-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_remove_house_photo2_remove_house_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='photo2',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='photo3',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo1',
            field=models.CharField(max_length=255),
        ),
    ]
